### ISSUE TITLE
Added to npm registry

### ISSUE THREAD

**Issue by paulpatarinski** [MBuchalik/cordova-build-architecture#4]
FYI I added this plugin to the npm registry so it is easier to install  : https://www.npmjs.com/package/cordova-plugin-build-architecture

**Comment by MBuchalik** [comment]
Sounds great 👍 
Just out of curiosity - why have you changed the version numbers to 1.0.4? The latest version published on github is 1.0.3

**Comment by paulpatarinski** [comment]
Removed it...will republish in 24h with the correct version. I had pushed 1.0.3 already & needed to make a small change. Renamed the id to cordova-plugin-build-architecture to match the other plugin names

**Comment by MBuchalik** [comment]
Ah ok, thanks for the clarification. Since I have never published anything to npm, I thought that (for some reason) some more changes were needed.

**Comment by paulpatarinski** [comment]
Sorry had no luck downgrading to 1.0.3 due to this http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f

actually even worst now I had to bump to 1.0.5. I will submit a PR with the version update 

https://www.npmjs.com/package/cordova-plugin-build-architecture
