### ISSUE TITLE
path changes in PGB 8.0.0 / cordova-android 7.0.0

### ISSUE THREAD

**Issue by tisdall** [MBuchalik/cordova-build-architecture#6]
apparently there have been path changes in the latest crosswalk version and this plugin is looking only for the old version

Here's the change made:  https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/3f43da977bfcc498c2668535b757f26ed3b323a4

I have zero knowledge of gradle or I'd attempt some sort of PR, but is there a way to try reading the new XML path and then fail over to the old if not found?

**Comment by MBuchalik** [comment]
Could you try the latest changes I published on master? It should add compatibility with PGB 8.0.0 and still be compatible with older versions. Does it work with your configuration?

**Comment by tisdall** [comment]
@MBuchalik - Aces!  Thank you so much!  Maybe make it 1.0.4?

BTW, if you test it yourself, there's an issue preventing using the latest crosswalk in PGB and I had to use someone else's repository to get it to compile:  https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205#issuecomment-371881536

**Comment by MBuchalik** [comment]
Thanks for your feedback! I have just created a new version (v1.0.4).

Yeah, I have already been using cordova-android-support-gradle-release because of another plugin that suddenly couldn't be used anymore 😄

**Comment by writeosahon** [comment]
@MBuchalik @tisdall Hello. First off, thanks to @MBuchalik for responding so quickly to all issues 👍.
Thanks again for all your work 👏 
2nd to @tisdall , there is actually no need to use another version of crosswalk for building. Simplify use this plugin: [https://github.com/dpa99c/cordova-android-support-gradle-release](url) and specify the correct version for the Android Support libraries . Most plugins use Version 27+ , but about a week ago google released Version 28. This is causing plugins that didn't pin their build to a specific version to fetch the latest version, hence the broken builds.

**Comment by tisdall** [comment]
@writeosahon - thanks..  I just discovered cordova-android-support-gradle-release shortly after posting my message and then posted a reply to the issue I linked to.

I also make sure to pin my dependencies so my config.xml now has: `<plugin name="cordova-build-architecture" spec="https://github.com/MBuchalik/cordova-build-architecture.git#v1.0.4" source="git" />`.  Nothing worse then making a small change and then finding you can't compile because a dependency has changed something and released a new version.

... now I just have to figure out why PGB is naming my apk "app-armv7-release.apk" instead of using `<name>` from the config.xml (as it used to do).

**Comment by matrixreal** [comment]
hello
i got build failed can anyone help me ?
here is what i do
cordova create test com.test.com
cd test
add cordova plugin add cordova-plugin-crosswalk-webview
cordova platform add android@7.1.0
cordova build android --release

got these build fail error
![cordova-error](https://user-images.githubusercontent.com/6823974/37915022-d5888048-3118-11e8-9f01-bf7362194595.png)

**Comment by MBuchalik** [comment]
@matrixreal This repository does not really conver anything directly related to Crosswalk. I would suggest posting a question in Crosswalk's issue page. Also, remember to include all plugins that can be found in your config.xml. One thing that might help you (or not since I can't see the whole error message in your image) is the plugin cordova-android-support-gradle-release we discussed above.

**Comment by matrixreal** [comment]
@MBuchalik 
i'm not using any other plugin
oh you say this plugin cordova-android-support-gradle-release ?
so i just need to add it or i have to do some changes ?
thanks a lot

**Comment by MBuchalik** [comment]
@matrixreal I don't see the whole error message on your screen shot. So this was just an idea since recently a lot of errors occur because of an alpha version of the Android support library. Simply try if adding the plugin helps (no other configuration should be required). If that doesn't help, please create an issue in the Crosswalk repo. The question isn't related to cordova-build-architecture. :smile:
