### ISSUE TITLE
Support for cordova-android >= 7

### ISSUE THREAD

**Issue by abrunetta** [MBuchalik/cordova-build-architecture#8]
When using npm to install cordova-plugin-build-architecture, somehow it's not the last release (1.0.4) that adds support for cordova-android >= 7.

**Comment by MBuchalik** [comment]
Have you tried installing the plugin using git? Does it work here?

The npm repo isn't maintained by me (see #5) so I can't tell when the updates will be added.

**Comment by abrunetta** [comment]
Yes, when installing from git it works correctly.
So I guess the npm package is using an outdated version. I'll post the issue there.
Thanks!

**Comment by MBuchalik** [comment]
OK, thanks for testing it with the git version! Closing the issue for now - if you have any additional questions, feel free to comment on this issue or to create a new one.
